#!/bin/sh
# Hiveton H5000M 首次启动个性化设置

#---------- 系统 ----------
uci -q batch <<-EOF
	set system.@system[0].hostname='Hiveton_H5000M'
	set system.@system[0].timezone='CST-8'
	set system.@system[0].zonename='Asia/Shanghai'
	set system.@system[0].ttylogin='0'
	set system.@system[0].log_size='128'
	set system.@system[0].urandom_seed='0'
	delete system.ntp
	set system.ntp=timeserver
	set system.ntp.enabled='1'
	set system.ntp.enable_server='0'
	add_list system.ntp.server='ntp.tencent.com'
	add_list system.ntp.server='ntp.aliyun.com'
	add_list system.ntp.server='ntp.ntsc.ac.cn'
	add_list system.ntp.server='ntp.tuna.tsinghua.edu.cn'
	commit system
EOF

#---------- root 默认密码 ----------
# 密码：admin（MD5-crypt 哈希，必须用单引号，双引号会被 shell 展开成空密码）
# 换密码用：openssl passwd -1 你的新密码
sed -i 's|^root:[^:]*:|root:$1$Op3nWrtX$l7bDHUU8J8QiMrMHTsaL51:|' /etc/shadow

#---------- 无线 ----------
# 若无线配置尚未生成，先生成
[ -f /etc/config/wireless ] || /sbin/wifi config

. /lib/functions.sh

WIFI_KEY='ljx2026@.'

set_radio() {
	local radio="$1"
	uci -q delete wireless.$radio.disabled
}

set_iface() {
	local iface="$1"
	local device band ssid

	config_get device "$iface" device
	[ -n "$device" ] || return 0

	band=$(uci -q get wireless.$device.band)
	case "$band" in
		2g) ssid='Hiveton-2G' ;;
		5g) ssid='Hiveton-5G' ;;
		6g) ssid='Hiveton-6G' ;;
		*)  ssid='Hiveton' ;;
	esac

	uci -q set wireless.$iface.ssid="$ssid"
	uci -q set wireless.$iface.encryption='psk2+ccmp'
	uci -q set wireless.$iface.key="$WIFI_KEY"
	uci -q delete wireless.$iface.disabled
}

config_load wireless
config_foreach set_radio wifi-device
config_foreach set_iface wifi-iface
uci -q commit wireless

exit 0
